import = [
  "~/.config/alacritty/themes/solarized_dark.toml"
]

live_config_reload = true

[env]
# TERM = "xterm-256color"
TERM = "alacritty"

[keyboard]
bindings = [
 { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
 { key = "V", mods = "Control|Shift", action = "Paste" },
]


[mouse]
hide_when_typing = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

